### ISSUE TITLE
Font Awesome 图标不兼容问题

### ISSUE THREAD

**Issue by gxres042** [KawaiiZapic/Present#4]
## 问题详细信息
对于 fa* 开头的 Font Awesome 图标代码无法使用，例如 fas fa-blog。
**目前测试来看，只能使用例如 fa fa-book 这样的 Font Awesome 图标代码。**

## 测试平台
Windows 10 Education 64 Bit
Microsoft Edge(Chromium)

## 主页加载
由 Vercel APP 提供支持。

## 建议解决方案
更新 Font Awesome 图标的使用代码。

*请尽快处理，以便我及时对我的主页进行下一步的维护，谢谢！*

**Comment by KawaiiZapic** [comment]
不处理.  
README.md明确指出了图标列表的链接.  
仅支持Font Awesome 4,不支持Font Awesome 5,由于4与5的图标尺寸存在差异,直接替换会导致显示偏差,或进行大量修改.  
所以暂不考虑在master分支上更换.

你可以fork后自行修改并修正更换导致的偏差.
