### ISSUE TITLE
将网站使用cloudflare cdn并开启cloudflare的强制https后会导致网站卡在loading界面

### ISSUE THREAD

**Issue by endlessland** [KawaiiZapic/Present#8]
将网站使用cloudflare cdn并开启cloudflare的强制https后会导致网站卡在loading界面
![image](https://user-images.githubusercontent.com/77194294/195671488-627d6337-34ca-47f3-b6cc-7d906b7f7a7e.png)

**Comment by endlessland** [comment]
经过检查，与强制https无关，只要开启cdn就会导致卡住

**Comment by Misaka13514** [comment]
在 `script` 添加 `data-cfasync="false"`
